/*
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 *
 * Triangle:    T_(n)=n(n+1)/2      1, 3, 6, 10, 15, ...
 * Pentagonal:  P_(n)=n(3n−1)/2     1, 5, 12, 22, 35, ...
 * Hexagonal:   H_(n)=n(2n−1)       1, 6, 15, 28, 45, ...
 * 
 * It can be verified that T_(285) = P_(165) = H_(143) = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 *
 * Anwser:  1533776805
 */

#include <stdlib.h>
#include <inttypes.h>

#define Tn(n)  n*(n+1)/2
#define Pn(n)  n*(3*n-1)/2
#define Hn(n)  n*(2*n-1)

int problem45()
{
    int64_t it = 285, ip = 165, ih = 143;

    do {
        ih++;
        while(Pn(ip) < Hn(ih)) {
            ip++;

            while(Tn(it) < Pn(ip)) {
                it++;
            }
        }
    } while (Tn(it) != Pn(ip) || Tn(it) != Hn(ih));

    return Tn(it);
}

