#include <stdio.h>
#include <stdlib.h>

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms.
 *
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * Find the sum of all the even-valued terms in the sequence which do not exceed
 * four million.
 *
 * Answer: 4613732
 */
int problem2(int fmax)
{
    int f0 = 0, f1 = 1, f;
    int fn = 0, fn1 = 0, fn2 = 0;
    int n;
    int sum = 0;

    // Build a Fibonacci sequence
    for (n = 0; fn1 < fmax; n++) {
        if (n == 0) { // First step of F sequence
            fn = f0;
            fn1 = f1;
            fn2 = fn + fn1;
        } else { // All otner steps
            fn = fn1;
            fn1 = fn2;

            fn2 = fn + fn1;
        }

        // Calc sum of even F sequence numbers
        if (fn % 2 == 0) {
            sum += fn;
        }
    }

    return sum;
}
